#[cfg(feature = "runtime-generation")]
fn main() -> std::process::ExitCode {
    use perfect_pi::{RoundingMode, generate_pi_ascii_with_rounding, runtime_pi_ascii_len};

    let decimal_places = match std::env::args().nth(1) {
        Some(value) => match value.parse::<usize>() {
            Ok(value) => value,
            Err(error) => {
                eprintln!("invalid decimal-place count: {error}");
                return std::process::ExitCode::FAILURE;
            }
        },
        None => 100,
    };

    let rounding = match std::env::args().nth(2).as_deref() {
        None | Some("trunc") | Some("toward-zero") => RoundingMode::TowardZero,
        Some("away") | Some("away-from-zero") => RoundingMode::AwayFromZero,
        Some("floor") | Some("toward-negative") => RoundingMode::TowardNegativeInfinity,
        Some("ceil") | Some("toward-positive") => RoundingMode::TowardPositiveInfinity,
        Some("round") | Some("nearest-even") => RoundingMode::NearestTiesToEven,
        Some("nearest-away") => RoundingMode::NearestTiesAwayFromZero,
        Some(mode) => {
            eprintln!("unknown rounding mode: {mode}");
            eprintln!("use trunc, away, floor, ceil, round/nearest-even, or nearest-away");
            return std::process::ExitCode::FAILURE;
        }
    };

    let required = match runtime_pi_ascii_len(decimal_places) {
        Ok(required) => required,
        Err(error) => {
            eprintln!("cannot represent requested precision: {error}");
            return std::process::ExitCode::FAILURE;
        }
    };
    let mut output = vec![0_u8; required];
    let written = match generate_pi_ascii_with_rounding(decimal_places, rounding, &mut output) {
        Ok(written) => written,
        Err(error) => {
            eprintln!("generation failed: {error}");
            return std::process::ExitCode::FAILURE;
        }
    };
    match std::str::from_utf8(&output[..written]) {
        Ok(text) => println!("{text}"),
        Err(error) => {
            eprintln!("generated bytes were not UTF-8: {error}");
            return std::process::ExitCode::FAILURE;
        }
    }
    std::process::ExitCode::SUCCESS
}

#[cfg(not(feature = "runtime-generation"))]
fn main() {
    eprintln!("enable the runtime-generation feature to run this example");
}
