"""Generate or verify the independently computed runtime pi prefix."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from verify_reference import chudnovsky_pi, gauss_legendre_pi

OUTPUT = ROOT / "src" / "runtime_precomputed.rs"
FAST_DECIMAL_PLACES = 10_000
EXTRA_DECIMAL_PLACES = 32
CHUNK_BYTES = 100

def render() -> str:
    places = FAST_DECIMAL_PLACES + EXTRA_DECIMAL_PLACES
    precision = places + 8
    chudnovsky = format(chudnovsky_pi(precision), "f")
    gauss_legendre = format(gauss_legendre_pi(precision), "f")
    required = places + 2

    if chudnovsky[:required] != gauss_legendre[:required]:
        raise RuntimeError("independent pi generators disagree")

    pi_text = chudnovsky[:required]
    if not pi_text.startswith("3.") or len(pi_text) != required:
        raise RuntimeError("unexpected generated pi text shape")

    chunks = [
        pi_text[index : index + CHUNK_BYTES]
        for index in range(0, len(pi_text), CHUNK_BYTES)
    ]

    lines = [
        "//! Generated by scripts/generate_runtime_prefix.py.",
        "//! Independently verified by Chudnovsky and Gauss-Legendre.",
        "",
        f"pub(super) const PRECOMPUTED_DECIMAL_PLACES: usize = {FAST_DECIMAL_PLACES:_};",
        "pub(super) const PRECOMPUTED_PI_ASCII: &[u8] = concat!(",
    ]
    lines.extend(f'    "{chunk}",' for chunk in chunks)
    lines.append(").as_bytes();")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    expected = render()

    if args.write:
        OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
        print(f"WROTE: {OUTPUT}")
        return 0

    actual = OUTPUT.read_text(encoding="utf-8")
    if actual != expected:
        print(
            "FAIL: src/runtime_precomputed.rs is not the independently generated prefix",
            file=sys.stderr,
        )
        return 1

    print(
        "PASS: runtime precomputed prefix matches independent "
        "Chudnovsky and Gauss-Legendre generation"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
